### ISSUE TITLE
[auth] spec: replace Clerk with Better Auth

### ISSUE THREAD

**Issue by regybean** [regybean/Trellis#218]
## Problem

`@acme/auth` is a Clerk wrapper. It re-exports Clerk's React components (`SignedIn`, `SignedOut`, `SignIn`, `SignUp`, `UserButton`, `useAuth`, `useUser`) behind a `'use client'` directive, and its backend half maps `@clerk/backend`'s `User` to a serializable shape. Clerk reaches 86 code files and 26 docs across the repo.

Replace it with Better Auth, self-hosted, without Keycloak or any other external identity provider.

## Why this blocks the bank work

`platform/trpc` and `shared/auth` are the two largest places Trellis and AIA both edited the same files (424 and 386 changed lines). Both diverged because AIA swapped Clerk for Better Auth. AIA has already made this migration and recorded it in its ADR 0031, so the design is proven rather than speculative, and Trellis converging on it removes most of the conflict area before the first full bank sync. The catalog conflict goes away too, since Trellis drops the same five Clerk entries AIA already deleted.

Sequencing is: invert the trpc entitlements coupling, then this migration, then the full sync.

## What Clerk touches today

- `packages/shared/auth/` entirely. `index.ts` re-exports `@clerk/clerk-react`; `types/admin.ts` imports `User` from `@clerk/backend`; `env.ts` validates `CLERK_SECRET_KEY`.
- `packages/platform/trpc/src/index.ts` types `InjectedAuth` as `userId` plus `sessionClaims`, which is Clerk's session shape.
- `CustomJwtSessionClaims` is declared in seven places: `shared/auth`, `platform/trpc`, all four feature packages' `global.d.ts`, and the feature generator template.
- `packages/shared/hooks/src/use-clear-cache-on-logout.ts` and `query-persister.ts`.
- `packages/shared/ui/src/widgets/user-detailed-management.tsx`, which renders Clerk's user fields.
- Both full apps: middleware, `<ClerkProvider>` in the root layout, sign-in and sign-up routes, `lib/admin.ts`, `env.ts`, `config.ts`, `trpc-route.ts`, Dockerfiles, eslint configs, and `apps/tanstack-start/src/lib/clerk-context.ts`.
- The slim apps mention Clerk only in comments and config, since they inject a constant principal. They should come through this untouched, which is a useful check that ADR 0010 holds.

## Decisions

**Better Auth tables live in a dedicated `auth` Postgres schema**, not the per-app `NEXT_PUBLIC_WEBAPP` schema. Identity is shared across apps that use the same database, and per-app identity stores would mean a user exists four times. This is a deliberate exception to ADR 0008 and needs writing down. AIA made the same call.

**Hand-author the Drizzle schema** rather than using `@better-auth/cli generate`. The CLI does not emit `pgSchema()` on the stable line, and the four tables are small. The backend suite is the check that cross-schema wiring resolves at runtime.

**`@acme/auth` stops shipping React components.** Under Clerk the package existed largely to re-export Clerk's prebuilt UI behind a `'use client'` boundary. Better Auth ships no UI, so the client barrel and the `'use client'` hack both go. The app owns `createAuthClient`, and `@acme/auth` exports the inferred `Session` type plus the server instance. This is a real reduction: the `'use client'` directive in `index.ts` currently exists to stop the Next RSC graph evaluating `@clerk/shared` into `swr`, and that problem disappears with the dependency.

**Auth becomes stateful.** Clerk sessions are external; Better Auth sessions are rows. `@acme/auth` gains a `@acme/db` dependency, auth tables come under app-owned `db:push` and `db:migrate`, and the backend test suite needs the `auth` schema provisioned (ADR 0021).

**Fix `@t3-oss/env-nextjs` while in here.** `@acme/auth` is a shared package importing the Next.js flavour of the env library, which is a framework dependency in a layer that is not supposed to have one. Move to `@t3-oss/env-core`, as AIA did.

**Roles move from JWT claims to a column.** `CustomJwtSessionClaims` has no Better Auth equivalent. Role lives on the user row. All seven declarations change, including the generator template, so new features scaffold without Clerk vocabulary.

**Neutral session wrapper in `platform/trpc`.** Pin the injected type to `{ user: InjectedUser | null }` so the provider is an app-side mapping. `InjectedUser` is already an augmentable global; the wrapper around it was the part that had absorbed Clerk's shape. ADR 0003 claims the auth seam is app-owned, which was true for resolution and false for the session type. Update it.

## The expensive part

Clerk's prebuilt components have no Better Auth equivalent. Sign-in, sign-up, the user button, and the admin user-management widget all need authoring against `@acme/ui`. This is the bulk of the work and the main risk to the estimate. `user-detailed-management.tsx` in particular reads Clerk's `emailAddresses` array, `imageUrl`, `publicMetadata`, and `lastSignInAt`, and Clerk's user-management API has no direct replacement without Better Auth's admin plugin.

Sign-in and sign-up UI is worth building in `@acme/ui` rather than per app, since both full apps need it and it is not domain-tied. That also makes it bank content.

## Work

1. Rewrite `@acme/auth`: server instance, Drizzle schema in the `auth` pgSchema, env via `env-core`, `Session` type export, delete the client barrel.
2. Neutralise the session type in `@acme/trpc` and remove `CustomJwtSessionClaims` from all seven declarations plus the generator template.
3. Author sign-in, sign-up, and user-button components in `@acme/ui`.
4. Rework `user-detailed-management.tsx` and `lib/admin.ts` in both apps against Better Auth's admin plugin.
5. Wire both full apps: route handler, `createAuthClient`, root layout provider, sign-in and sign-up routes, middleware, env, config, Dockerfiles.
6. Drop the five Clerk catalog entries and the Clerk dependencies from both app manifests.
7. Update ADR 0003 and ADR 0013; write the new ADRs below. Update `docs/getting-started.md`, `docs/whats-included.md`, `README.md`, `CLAUDE.md`, `AGENTS.md`, and the four app `CONTEXT.md` files.
8. Confirm both slim apps are untouched.

## Risks

- The UI authoring in steps 3 and 4 is the schedule risk, not the auth wiring.
- Existing Clerk users have no migration path. If any deployment has real users, that needs its own plan. For a template repo it is probably a non-issue, but it should be stated rather than assumed.
- Auth tables in a shared `auth` schema mean the four apps share an identity store. That is the intent, but it is a behaviour change from Clerk instances being separable per app.

## Out of scope

- Keycloak or any external identity provider. AIA needs one; Trellis does not.
- Migrating existing Clerk user data.
- Organisations, teams, or multi-tenancy.
- Copying AIA's code. AIA's implementation is a reference to read, not content to import, and back-flow from AIA is gated separately.

## Open questions

- Which sign-in methods ship by default? Email and password only, or a social provider too?
- Does the admin plugin cover what `user-detailed-management.tsx` needs, or does that widget get cut back?

## ADRs

New:
1. Better Auth replaces Clerk, self-hosted, sessions stored in Postgres
2. Auth tables live in a dedicated `auth` schema, outside the per-app `NEXT_PUBLIC_WEBAPP` schema, as an exception to ADR 0008

Update:
- ADR 0003, which overstates what the auth seam covers. The resolver was app-owned; the session type was not.
- ADR 0013, which assumes Clerk's user shape for the admin widgets.

**Comment by regybean** [comment]
Blocks #219 step 5 (the full bank sync). Steps 1 and 2 of #219 (tooling/root template, then `shared/ui`) do not depend on this and can start in parallel.

**Comment by regybean** [comment]
## Proposal: drop the `InjectedUser` global, make the session type importable

This challenges one of the decisions above:

> **Neutral session wrapper in `platform/trpc`.** Pin the injected type to `{ user: InjectedUser | null }` so the provider is an app-side mapping. `InjectedUser` is already an augmentable global; the wrapper around it was the part that had absorbed Clerk's shape.

#220 landed the wrapper and it works. The global did not survive contact as well, and I think step 2 should change before the Better Auth work starts.

### What #220 shows

`interface InjectedUser` is now declared in eight files: `@acme/trpc`, `@acme/auth`, chat, feedback, ingest, billing, notifications, and the generator template. That is one more than the seven `CustomJwtSessionClaims` declarations the ticket set out to delete.

It is more than a naming problem, because "augmentable" is not what the mechanism does here. TypeScript merges declarations within a program. Features compile in isolation against `dist`, so chat's `global.d.ts` is not adding a field to the platform's base, it is restating the whole interface. Eight copies, no merge.

Two consequences are already in the tree:

- `primaryEmailAddress` has two incompatible types for the same property. `@acme/auth` declares it as `Pick<User, 'primaryEmailAddress'>`, which is Clerk's `EmailAddress | null`. Billing declares it as `{ emailAddress: string } | null`. Nothing catches the mismatch because the two never share a program.
- `createMockUser` in `packages/platform/trpc/src/testing.ts` assigns to an unannotated local and returns that, to get past the excess-property check. The docblock admits it. A platform mock cannot type a field that only some consuming programs declare.

### Why owning the tables changes the answer

Under Clerk the session type came from a third party, so a global was the only way to describe it without every package importing `@clerk/backend`. Once role is a column and the tables are ours, `@acme/auth` can export the type inferred off the Drizzle `user` table. Features may depend on `@acme/auth` (features to shared), so they import it like any other type. The hand-written `Roles = 'admin' | 'user'` union goes too, since it comes off the column.

### The two packages that sit below `@acme/auth`

`@acme/trpc` is platform, and `@acme/notifications` has no `@acme/auth` dependency today, so neither can import that type. Neither needs it. `@acme/trpc` reads `session.user?.id` in three places and `role` in the `isAdmin` gate, and nothing else. Make the session a type parameter with a structural constraint instead of a global:

```ts
createFeatureTRPC<TUser extends { id: string; role?: string }>
```

That constraint is the platform's entire contract on the principal. The caller supplies the concrete type, so `createMockUser` becomes soundly typed and the excess-property dodge disappears.

### Effect on step 2

Today it reads "remove `CustomJwtSessionClaims` from all seven declarations plus the generator template." I would add: delete the eight `InjectedUser` global declarations, export `SessionUser` from `@acme/auth`, and make the platform's session generic. Bigger diff during the migration, fewer files afterwards, and one of the two packages Trellis and AIA both edited heavily stops carrying an ambient global at all.

One caveat I cannot check from here. If AIA kept the augmentable global, this diverges from AIA, which cuts against the "removes most of the conflict area before the first full bank sync" argument for doing the migration. Worth confirming against AIA's ADR 0031 before committing to it.

*Raised from the automated review of #230.*
